In [3]:
import numpy as np
N = 13
M = 13

tablero = np.zeros((N, M), dtype=int)

def item(aux):
    a=np.zeros((N, M), dtype=int)
    for i in range(N):
        for j in range(M):
            vida=0
            #evaluar
            if i-1>=0:
                if j-1>=0:
                    if aux[i-1,j-1]==1:
                        vida+=1
                if j+1<M:
                    if aux[i-1,j+1]==1:
                        vida+=1
                if aux[i-1,j]==1:
                    vida+=1
            if i+1<N:
                if j-1>=0:
                    if aux[i+1,j-1]==1:
                        vida+=1
                if j+1<M:
                    if aux[i+1,j+1]==1:
                        vida+=1
                if aux[i+1,j]==1:
                    vida+=1
            if j-1>=0:
                if aux[i,j-1]==1:
                    vida+=1
            if j+1<N:
                if aux[i,j+1]==1:
                    vida+=1
            a[i,j]=vida
    for i in range(N):
        for j in range(M):
            if tablero[i,j]==1:
                if a[i,j]<2:
                    tablero[i,j]=0
                if a[i,j]>3:
                    tablero[i,j]=0
            else:
                if a[i,j]==3:
                    tablero[i,j]=1
tablero[3, 1:4] = 1
tablero[2, 3] = 1
tablero[1, 2] = 1

for i in range(10):
    item(tablero)
    print(tablero)
    print("\n\n")

[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]



[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]



[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 